### PR TITLE
[WIP] Flavors implementation

### PR DESCRIPTION
**Pull request by vlazdra**
Hi guys, since I needed the flavor implementation for my project, and this library has some room for improvements I wanted to give it a shoot and implement the support for multiple flavors.

I have extended the run command to include the flavor setup:
```dart
// If you have a flavor called production you would do this:
flutter pub run flutter_native_splash:create --flavor production

// For a flavor with a name staging you would provide it's name like so:
flutter pub run flutter_native_splash:create --flavor staging

// And if you have a local version for devs you could do that:
flutter pub run flutter_native_splash:create --flavor development
```
If you pass an invalid flavor value, you will get an error and exit the process, and if you don't pass any value to the CLI, you will just setup the project as if there are no flavors.

Wanted to get your input on the changes, for now I've only implemented the **Android** integration as it was the closes to me, will dig in to **iOS** and **Web** (if possible not sure)

Any feedback or guidance would be very appreciated! @jonbhanson @henriquearthur 
> Note: The flavor setup was done manually. I didn't use any library.

### CODE REVIEW

**Comment by vlazdra** [comment]
The work in this PR would resolve the issue #160

**Comment by vlazdra** [comment]
Hi guys. I continued to do some work on the flavor implementation today. In the meantime cleaned up some leftovers from the Android setup.

While Android was pretty easy to setup and does not required the developer to basically do anything iOS is a bid different, but only because we can't interact with the `project.pbx` file in order to link the newly created files when they are generated.

The steps to implement for iOS:
1. Step
```dart
// The commands are the same for iOS as for Android so no changes there as expected.
// If you have a flavor called production you would do this:
flutter pub run flutter_native_splash:create --flavor production

// For a flavor with a name staging you would provide it's name like so:
flutter pub run flutter_native_splash:create --flavor staging

// And if you have a local version for devs you could do that:
flutter pub run flutter_native_splash:create --flavor development
```
2. Step
When everything get's generated we need to add the newly created Storyboards to the project.
- Open the iOS Flutter project in Xcode (open the Runner.xcworkspace)
- Find the newly created Storyboard files at the same location where the original is `{project root}/ios/Runner/Base.lproj`
- Select all of them and drag and drop into Xcode, directly to the left hand side where the current LaunchScreen.storyboard is located already
- After you drop your files there Xcode will ask you to link them, make sure you select 'Copy if needed'
- This part is done, you have linked the newly created storyboards in your project.

3. Step
Xcode still doesn't know how to use them, so we need to specify for all the current flavors (schemes) which file to use and to use that value inside the Info.plist file.
- Open the iOS Flutter project in Xcode (open the Runner.xcworkspace)
- Click the Runner project in the top left corner (usually the first item in the list)
- In the middle part of the screen, on the left side, select the Runner target
- On the top part of the screen select Build Settings
- Make sure that 'All' and 'Combined' are selected
- Next to 'Combine' you have a '+' button, press it and select 'Add User-Defined Setting'
- Once you do that Xcode will create a new variable for you to name. Suggestion is to name it `LAUNCH_SCREEN_STORYBOARD`
- Once you do that, you will have the option to define a specific name for each flavor (scheme) that you have defined in the project. **Make sure that you input the exact name of the LaunchScreen.storyboard that was created by this tool**
 - Example: If you have a flavor Development, there is a Storyboard created name `LaunchScreenDevelopment.storyboard`, please add that name (without the storyboard part) to the variable value next to the flavor value
 - After you finish with that, you need to update `Info.plist` file to link the newly created variable so that it's used correctly
 - Open the Info.plist file
 - Find the entry called 'Launch screen interface file base name'
 - The default value is 'LaunchScreen', change that to the variable name that you create previously. If you follow these steps exactly, it would be LAUNCH_SCREEN_STORYBOARD, so input this `${LAUNCH_SCREEN_STORYBOARD}`
 - And your done!

As always, if you have any questions and/or feedback, please let me know.

**Note**
If you guys agree with the implementation I would write up a tutorial on this and will update the README but not before you give me a thumbs up. :)

**Comment by darot-chen** [comment]
Thanks you @vlazdra . That's work really awesome. 👍👍👍

**Review by goatandsheep — APPROVED** [review]

**Comment by vlazdra** [comment]
Hi @jonbhanson, I've made the requested changes in the other PR.
Let me know when you go through this PR, and if you agree with the implementation, so that I can append the extra information about flavors into the README.md.

Also, I would need some time to write up the tutorial on the implementation of the flavors as well. 💪

**Comment by jonbhanson** [comment]
@vlazdra, your implementation looks fine.  Thanks for your work on this.  Please continue!  I will be happy to merge this when it is done.

**Comment by jonbhanson** [comment]
@vlazdra do you plan to finish this?

**Comment by jonbhanson** [comment]
No worries, @vlazdra, sounds fine.  I just was worried that I was creating too many conflicts with my other updates.  Thanks again for your work on this!

**Comment by vlazdra** [comment]
Hi @jonbhanson, sorry it took a bit longer to finish this. I've added the README instructions as well.
I've also updated the What's new part, but didn't change the version nor the CHANGELOG.md.

As always please let me know if you have any feedback regarding the changes! :)

**Comment by jonbhanson** [comment]
Thanks @vlazdra for your work on this!  I'll take a look, and hopefully if all is well it can go in the next release.

**Comment by esentis** [comment]
Thanks a lot for the awesome work, works flawlessly on Android, however I can't get it work with iOS flavors. 
Followed step by step the instructions, even redoing it many times but still in vein. Is there any example that I can follow ?

**Comment by vlazdra** [comment]
Hey @esentis maybe open an issue within the repo, with additional details as to what you tried and if there are any exceptions while trying to use the plugin.
A PR is not exactly the right place to ask for help. 😄

**Pull request merged**
