### PR TITLE
dependencies updated

### PR DESCRIPTION
**Pull request by sumitsharansatsangi**
Updated to the latest dependencies.

### CODE REVIEW

**Comment by jonbhanson** [comment]
@sumitsharansatsangi what is the reason for updating this sdk and flutter requirement? Won't that make this package incompatible for developers who are using older versions?  Does it provide some benefit that I am not aware of?

**Comment by sumitsharansatsangi** [comment]
@jonbhanson, I have fixed in the last commit. Thanks for your observation.

**Comment by jonbhanson** [comment]
Thanks @sumitsharansatsangi can you also resolve the conflicts with this PR?

**Comment by jonbhanson** [comment]
Actually, I think this has mostly been addressed in the latest release.  Thanks, @sumitsharansatsangi

**Pull request closed without merging**
