### PR TITLE
feat: choose between icon and image on android 12 splash

### LINKED ISSUE #293: Image isn't displayed on splash screen on Android 12
**Describe the bug**
Image is not being shown on splash screen

**To Reproduce**
1. add to dev_dependencies`flutter_native_splash: ^2.0.4`
2. add config to pubspec.yaml
```
flutter_native_splash:
  color: "#232323"
  image: assets/icon/test.png
```

3. run `flutter clean && flutter pub get && flutter pub run flutter_native_splash:create`
4. Launch app

**Expected behavior**
Show the image on top of the background

**Screenshots**

**Device (please complete the following information):**
 - Device: Pixel 3a XL
 - OS: Android 12

```
**Flutter doctor**
[√] Flutter (Channel stable, 2.10.1, on Microsoft Windows [VersiÃ³n 10.0.19044.1526], locale es-ES)
    • Flutter version 2.10.1 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (6 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at S:\ADB
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31729.503
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\Kevin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [VersiÃ³n 10.0.19044.1526]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 98.0.4758.82
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 98.0.1108.50

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Additional context**
I'm sure the image works as I'm using the same for the Icon.

### PR DESCRIPTION
**Pull request by JCQuintas**
- Add behaviour to choose between using the App's default icon or the provided splash screen image.
- Documentation for new property

Fixes #293

### CODE REVIEW

**Comment by jonbhanson** [comment]
@JCQuintas thanks for this PR.  Unfortunately, I think it will be too limited for this package's users: Since the Android 12 icon must be square, users may want to choose a different image for Android 12 and prior versions of Android.  However, your work served to inspire me to add better Android 12 support.

**Comment by JCQuintas** [comment]
Glad to have helped :)

**Comment by miguelflores1993** [comment]
is this already in the new versions?

**Comment by jonbhanson** [comment]
> is this already in the new versions?

Yes, although implemented slightly differently than in this PR.  See the readme for info on how to use this.

**Pull request merged**
