### PR TITLE
#18 support fill property on iOs

### LINKED ISSUE #18: Support 'fill' property on iOS
Currently `fill` property for using an image on full screen only works in Android, we need to implement the functionality on iOS.

### PR DESCRIPTION
**Pull request by Chralu**
Hi,

I added some code to enable `fill` property for iOS (Fixes #18).
Changes consists in :
 -  adding two constraints 
 - changing the `ImageView` `contentMode`.

To ease XML manipulation, I switched `storyboard` manipulation to https://pub.dev/packages/xml.

Hope you like it.
Cheers :)

### CODE REVIEW

**Comment by shinriyo** [comment]
@henriquearthur hey. do you still maintenance it yet?

**Comment by shinriyo** [comment]
Did you gave up?

**Comment by yourshinsuke** [comment]
@henriquearthur

**Comment by eliabieri** [comment]
is there an update on this?

**Comment by jonbhanson** [comment]
@Chralu can you resolve the conflicts so this fork can be merged?  Thanks,

**Comment by shinriyo** [comment]
@jonbhanson you came back

@Chralu Could you fix it?

**Comment by shinriyo** [comment]
do you know how to fix?

**Pull request closed without merging**
